//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppReporteAgendamiento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TRANSACCION_IVR
    {
        public int IDIVRV { get; set; }
        public string CONVERSATIONID { get; set; }
        public string IDENTIFICACIONIVR { get; set; }
        public string FLUJO { get; set; }
        public string TRANSACCIONESIVR { get; set; }
        public Nullable<System.DateTime> FECHAIVR { get; set; }
    }
}
