//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppReporteAgendamiento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FLUJOS
    {
        public int IDFLUJO { get; set; }
        public string NOMBREFLUJO { get; set; }
    }
}
