//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppReporteAgendamiento.fonts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ENCUESTA
    {
        public int ID { get; set; }
        public string PREGUNTA_1 { get; set; }
        public string CONVERSATION_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string PREGUNTA_2 { get; set; }
    }
}
