//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppReporteAgendamiento.fonts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FORMULARIO
    {
        public long ID_FORMULARIO { get; set; }
        public string ID_INTERACTION { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string COMENTARIO { get; set; }
        public string EMPRESA { get; set; }
        public string SERVICIO { get; set; }
        public string CATEGORIA { get; set; }
        public string ACCION { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string AGENTE { get; set; }
        public string EMISOR_SOLICITUD { get; set; }
        public string TIENDA { get; set; }
        public string EMISOR_SOLICITUDQ { get; set; }
        public string TIENDA1 { get; set; }
    }
}
